export enum Role {
  MEMBER = "MEMBER",
  ADMIN = "ADMIN",
  MODERATOR = "MODERATOR",
  SECURITY_ANALYST = "SECURITY_ANALYST",
  PENETRATION_TESTER = "PENETRATION_TESTER",
  NETWORK_ADMINISTRATOR = "NETWORK_ADMINISTRATOR",
}
